#!/bin/bash
#
# Credit goes, where credit's due: @wjlroe
#
# Start tmux using this small wrapper script:
#
# #!/bin/bash
# $HOME/bin/ssh_auth
# SSH_AUTH_SOCK=$HOME/.ssh/current_ssh_auth_sock
# tmux attach

function set_current_ssh_auth_sock {
    current_ssh_auth_sock=${1:-~/.ssh/current_ssh_auth_sock}

    if [ ! -e "$current_ssh_auth_sock" -o -h "$current_ssh_auth_sock" ]
    then
        if file -L "$current_ssh_auth_sock" >/dev/null
        then
            SSH_AUTH_SOCK="$current_ssh_auth_sock"
        else
            rm -f "$current_ssh_auth_sock"
            ln -s $SSH_AUTH_SOCK "$current_ssh_auth_sock"
            SSH_AUTH_SOCK="$current_ssh_auth_sock"
        fi
    else
        echo "error: $current_ssh_auth_sock is not a symlink"
    fi
}


current_ssh_auth_sock=~/.ssh/current_ssh_auth_sock

if [[ -n "$SSH_AUTH_SOCK" ]] \
    && [[ "$SSH_AUTH_SOCK" != "$current_ssh_auth_sock" ]] \
    && ! echo "$SSH_CLIENT" | fgrep '192.168' -q
then
    set_current_ssh_auth_sock "$current_ssh_auth_sock"
fi
